server:
  port: ${PORT:8080}
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: true
        same-site: Lax

jwt:
  secret: ${JWT_SECRET_KEY}`
  issuer: login-ex
  access-ttl-seconds: 1800
  refresh-ttl-seconds: 1000000

spring:
  config:
    import: optional:file:.env.properties
    profiles:
      active: local

  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT:3306}/Login
    username: ${USER_NAME:root}
    password: ${USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # data.sql run (always or never)
  sql:
    init:
      mode: never

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    # run data.sql
    defer-datasource-initialization: true